# Site settings
title: Chris & Nikita
email: chris@baclig.me
url: http://www.chrisandnikita.com
description: "We're getting married and can't wait to celebrate with you!"
baseurl: ""
host: 0.0.0.0 # listen to LAN connections
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty

# Possible values
# `chi` - Chicago
# `lbc` - Long Beach
context: chi

locations:
  hilton: &hilton_location
    location_name: Hilton Chicago
    address1: 720 S Michigan Ave.
    address2: Chicago, IL 60605
    coordinates: 41.872592,-87.62481
    google_maps_url: https://www.google.com/maps/place/Hilton+Chicago/@41.8725329,-87.6248502,17z/data=!4m7!1m4!3m3!1s0x880e2c99242c7a2f:0x4de3d4bb09dba1!2sHilton+Chicago!3b1!3m1!1s0x880e2c99242c7a2f:0x4de3d4bb09dba1
  vashi: &vashi_location
    location_name: Vashi Residence
    address1: 211 N Savanna Ct.
    address2: Lake Forest, IL 60045
    coordinates: 42.243377,-87.878189
    google_maps_url: https://www.google.com/maps/place/211+N+Savanna+Ct,+Lake+Forest,+IL+60045/@42.244292,-87.8793387,17z/data=!3m1!4b1!4m2!3m1!1s0x880f951707bd6ae1:0xee4caaaf8316d979
  navy_pier: &navy_pier_location
    location_name: Navy Pier Grand Ballroom
    address1: 600 E Grand Ave.
    address2: Chicago, IL 60611
    coordinates: 41.891932,-87.611652
    google_maps_url: https://www.google.com/maps/place/Navy+Pier/@41.8813917,-87.616019,15z/data=!4m5!1m2!2m1!1snavy+pier!3m1!1s0x880e2b4d91f12edb:0xd0acdb96b088a4dc
  st_michael: &st_michael_location
    location_name: St. Michael in Old Town
    address1: 1633 N Cleveland Ave.
    address2: Chicago, IL 60614
    coordinates: 41.911652,-87.641253
    google_maps_url: https://www.google.com/maps/place/St+Michael+in+Old+Town/@41.912635,-87.6408956,15z/data=!4m2!3m1!1s0x0:0xe227f2c7eb743c04
  aquarium: &aquarium_location
    location_name: Aquarium of the Pacific
    address1: 100 Aquarium Way
    address2: Long Beach, CA 90802
    coordinates: 33.762145,-118.196914
    google_maps_url: https://www.google.com/maps/place/Aquarium+of+the+Pacific/@33.7621508,-118.1991698,17z/data=!3m1!4b1!4m2!3m1!1s0x80dd313032cc7cb5:0x96dadf4782e15e96
  hyatt: &hyatt_location
    location_name: Hyatt Centric
    address1: 100 W Monroe St
    address2: Chicago, IL 60603
    coordinates: 41.8807816,-87.631112
    google_maps_url: https://www.google.com/maps/place/Hyatt+Centric+The+Loop+Chicago/@41.8807816,-87.631112,15z/data=!4m2!3m1!1s0x0:0xc98ca00ba03f886e?sa=X&ved=0ahUKEwiXxLXTlsjJAhXn4IMKHXNAD2oQ_BIIgAEwCg
  renaissance: &renaissance_location
    location_name: Renaissance Long Beach
    address1: 111 E Ocean Blvd
    address2: Long Beach, CA 90802
    coordinates: 33.7674056,-118.1915634
    google_maps_url: https://www.google.com/maps/place/Renaissance+Long+Beach+Hotel/@33.767385,-118.19168,15z/data=!4m2!3m1!1s0x0:0x19c2a818049de073?sa=X&ved=0ahUKEwiz1oXnsdTKAhXCHR4KHRmkC6sQ_BIIjQEwCg

hotels:
  chi:
    - name: Hilton Chicago
      phone: +1-312-922-4400
      reserve_url: https://resweb.passkey.com/go/VashiBacligWeding
      rate: $229/night
      description: Includes continental breakfast each morning
      <<: *hilton_location
    - name: Hyatt Centric
      phone: +1-312-236-1234
      reserve_url: https://aws.passkey.com/g/54381507
      rate: $199/night
      description: Centrally located in the middle of the loop
      <<: *hyatt_location
  lbc:
    - name: Renaissance Long Beach
      phone: +1-562-437-5900
      reserve_url: https://resweb.passkey.com/go/bacligwedding
      rate: $169/night
      description: A few blocks away from the aquarium
      <<: *renaissance_location

events:
  chi:
    - name: Mehndi Night
      date: Thursday, May 26, 2016
      time: 7pm
      attire: Casual
      description: A casual family gathering where henna is applied in intricate designs to the hands and feet of the bride and her female guests. Meant as one of many ritual adornments for the Hindu bride, it is said that the darker the henna turns out, the greater the love the bride has for her groom.  Mehndi artists also hide the groom’s name or initials into the bride’s henna design and it is her job to find them before the wedding. Traditionally, the bride is not allowed to work in her husband’s house until after the mehndi has completely faded. Further, with their hands covered in henna paste, the women of the party are unable to cook or serve during the Mehndi celebration, so the men are invited to feed and serve the women.
      transportation:
      <<: *vashi_location
    - name: Garba
      date: Friday, May 27, 2016
      time: 7pm
      attire: Semi-formal
      description: A night of traditional Gujarati folk dancing! Set to energetic music, garba is a style of group dance performed as a ritual homage to a the Hindu goddess of creation, Ambama. Garba is usually accompanied by Raas, a similar style of dance dedicated to the Hindu god Krishna that incorporates a set of sticks called Dandiya. Both are traditionally performed during the Gujarati festival of Navratri (“nine-nights”) and also as a precedent to special occasions such as weddings. Everyone is invited and encourage to join in the dancing - don’t worry, there will be tutorials!  And keep an eye out for a few special performances from close family and friends.
      transportation: Discounted self-parking will be available.
      <<: *hilton_location
    - name: Hindu Wedding
      date: Saturday, May 28, 2016
      time: 10am
      attire: Formal
      description: The Hindu wedding ceremony as described by the Vedas, the Hindu scriptures, is over 5,000 years old and is traditionally performed in the Sanskrit language. The ceremony commemorates the bride and groom no longer existing as two independent souls but as a spiritual oneness. Ceremonies include the Barat (Arrival of the Groom), Pokhna Vidhi (Welcoming of the Groom), Jai Mala (Exchange of Garlands), Vastra Granthi Bandhan (Tying the Knot), Mangalphera (Holy Circles around the Fire), and Saptapadi (Taking Life’s Seven Steps).
      transportation: Discounted self-parking will be available.
      <<: *hilton_location
    - name: Catholic Wedding
      date: Sunday, May 29, 2016
      time: 3pm
      attire: Black Tie Optional
      description: The traditional Catholic wedding is enhanced in Filipino culture by several traditions. Ceremonial sponsors or godparents are chosen by the betrothed as role models for their future married life and participate in the procession with the bridal party. Two separate candles are lit at the beginning of the ceremony, which the bride and groom then join into a single flame signifying the union of their two families. A veil is placed over the shoulders of the bride and groom during the ceremony, demonstrating the clothing of two individuals as one. A cord is then looped in a figure 8 and placed over the heads of the bride and group to signify everlasting fidelity.
      transportation: Limited self-parking available.
      shuttle: Transportation will also be provided between Hilton Chicago and St. Michael in Old Town.
      <<: *st_michael_location
    - name: Reception
      date: Sunday, May 29, 2016
      time: 5:30pm
      attire: Black Tie Optional
      description: Join us for dinner and dancing as we celebrate our marriage into the night!
      transportation: Complimentary valet parking will be available at Navy Pier. Follow signs for Navy Pier parking to the East Parking garage, entrance two.
      shuttle: Transportation will also be provided between St. Michael in Old Town, Navy Pier and Hilton Chicago.
      <<: *navy_pier_location
  lbc:
    - name: Reception
      date: Satuday, June 4, 2016
      time: 7pm
      attire: Semi-formal
      description: Join us for dinner and dancing as we celebrate our marriage into the night!
      transportation:
      <<: *aquarium_location

people:
  families:
    - pic: vashis.jpg
      name: The Vashis
      people: Pankaj, Glynis, Rohan and Cosmo
    - pic: bacligs.jpg
      name: The Bacligs
      people: Crispin, Bernadette, Jon and Samantha
  kids:
    - pic: nadiya.jpg
      name: Nadiya Kundu
      title: Flower Girl
    - pic: jaanvi.jpg
      name: Jaanvi Vashi
      title: Flower Girl
    - pic: levi.jpg
      name: Levi Lagrimas
      title: Ring Bearer
  her_side:
    - name: Samantha Baclig
      pic: samie.jpg
      role: Junior Bridesmaid
      description: Chris’ Sister
    - name: Ronak Vashi
      pic: ronak.jpg
      role: Bridesmaid
      description: Nikita’s Cousin
    - name: Trisha DaSilva
      pic: trisha.jpg
      role: Bridesmaid
      description: Nikita’s Cousin
    - name: Gabby Colaianni
      pic: gabbyc.jpg
      role: Bridesmaid
      description: Nikita’s High School Friend
    - name: Devyn Brown
      pic: devyn.jpg
      role: Bridesmaid
      description: Nikita’s College Roommate
    - name: Chelsea Barabas
      pic: chelsea.jpg
      role: Bridesmaid
      description: Nikita’s College Roommate
    - name: Tanya Aylward
      pic: tanya.jpg
      role: Bridesmaid
      description: Nikita’s College Friend
    - name: Sanjana Tandon
      pic: sanjana.jpg
      role: Bridesmaid
      description: Nikita’s College Friend
    - name: Leigha Winters
      pic: leigha.jpg
      role: Bridesmaid
      description: Nikita’s Post-College Roommate
    - name: Miriam Komisar
      pic: miriam.jpg
      role: Bridesmaid
      description: Nikita’s Medical School  Friend
    - name: Meagan Appleman
      pic: meagan.jpg
      role: Bridesmaid
      description: Nikita’s Medical School Friend
    - name: Gabby Aguilar
      pic: gabbya.jpg
      role: Bridesmaid
      description: Nikita’s Medical School Friend
  his_side:
    - name: Jonathan Baclig
      pic: jon.jpg
      role: Best Man
      description: Chris’ Brother
    - name: Rohan Vashi
      pic: rohan.jpg
      role: Groomsman
      description: Nikita’s Brother
    - name: Ryan Abad
      pic: ryan.jpg
      role: Groomsman
      description: Chris’ Cousin
    - name: Gabriel Mendoza
      pic: gabe.jpg
      role: Groomsman
      description: Chris’ High School Friend
    - name: Eric Ma
      pic: eric.jpg
      role: Groomsman
      description: Chris’ College Roommate
    - name: Rajan Patel
      pic: rajan.jpg
      role: Groomsman
      description: Chris’ College Roommate
    - name: Arpeet Shah
      pic: arpeet.jpg
      role: Groomsman
      description: Chris’ College Friend
    - name: Winston Lofton
      pic: winston.jpg
      role: Groomsman
      description: Chris’ College Friend
    - name: Scott Keyes
      pic: scott.jpg
      role: Groomsman
      description: Chris’ College Friend
    - name: Isaac Johnson
      pic: isaac.jpg
      role: Groomsman
      description: Chris’ Post-College Roommate
    - name: Dare Kolawale
      pic: dare.jpg
      role: Groomsman
      description: Chris’ Post-College  Roommate
faq:
  # TODO pre-line for dd's
  chi:
    - question: OMG what do I wear?
      answer: | The Garba night on Friday is primarily a night of Indian folk dancing, so be prepared to kick off your shoes, roll up your sleeves and get a light aerobic workout in!
        Ladies: ???
        Gentelmen: Think dress pants and a button-down shirt. Consider the jacket and tie optional.

        The Indian wedding ceremony on Saturday will be considerably less active (but will still include some dancing during the Baraat!) and is a more formal occassion.
        Ladies: ???
        Gentlemen: Break out the jacket and tie for this one, and thanks in advance for dealing with the midday heat!

        The Catholic ceremony and reception on Sunday will be a little more formal than Saturday's events.
        Ladies: ???
        Gentlemen: Jacket and ties are encouraged. For those with a tuxedo, this would be a good time to dust that off too, but it's by no means required to get past the bouncers (There won't be any bouncers.)

    - question: Do you have a sari I can borrow?
      answer: |
        Unfortunately, Nikita doesn't have anything else to lend out. :(
    - question: I have a pretty seriously allergy to [insert allergen here], can you accomodate me?
      answer: Yes! Get in touch with us ASAP, so we can make sure we keep any [insert allergen here] away from you!
    - question: Should I rent a car?
      answer: |
        No! For those guests coming from out of town, we will be providing transportation to and from all the events and the hotels. Even if you're staying somewhere else or want to explore more of the city, we'd highly recommend taking public transportation or cabs around downtown Chicago since parking in the city is hard to find and typically not cheap.

        Check out our section on <a href="/details/#getting-around">Getting Around</a> for more info.
    - question: What's happening Saturday night and Sunday morning?
      answer: Nothing! There are a lot of things going on during the weekend, so consider this half-time. Feel free to explore Chicago at your own pace, and rest up before the home stretch.
    - question: Is Chris going to ride in on a/an [insert large mammal here]?
      answer: |
        No, unless you're asking if Chris is going to ride a horse.
        Then the answer is yes - Chris is going to ride in on a white horse at
        the Baraat on Saturday.
    - question: Do I have to dance at the Garba?
      answer: No! Although we have a feeling you're going to want to once you see everyone doing it. Peer pressure is a real thing.
    - question: What kind of sick moves am I going to learn on Friday night?
      answer: ???

  lbc: false

google:
  key: AIzaSyB6rRW9hmltJZvoNLO7dewTmGqZn8LIRFU

calendar:
  ical: https://www.google.com/calendar/ical/baclig.com_fqi9g8u7mre0m4oaqj1p66608c%40group.calendar.google.com/public/basic.ics
  google_id: baclig.com_fqi9g8u7mre0m4oaqj1p66608c@group.calendar.google.com
