# Site settings
title: Chris & Nikita
email: chris@baclig.me
url: https://example.github.io
description: "Chris & Nikita"
baseurl: "/"

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Chris & Nikita

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

google:
  key: AIzaSyB6rRW9hmltJZvoNLO7dewTmGqZn8LIRFU
